In [9]:
import numpy as np

arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr_slice[1] = 30

In [15]:
arr_slice

array([ 5, 30,  7])

In [31]:
samples = np.random.standard_normal(size=(4, 4))
samples

array([[-0.20494476, -0.39833397, -0.77014968,  0.48771572],
       [-1.3224507 ,  0.56052165,  1.21830504, -1.30434625],
       [-1.35099982, -0.24241483, -0.00848362, -0.14978478],
       [ 0.0890464 , -1.20446087,  0.46213085, -0.84295884]])

In [29]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.grap, extent=[-5, 5, -5, 5])

NameError: name 'z' is not defined